inputdir: inputs/X

species:
    D: -421
    Dstar: 423

rapidity:
    plot: true

eventsperfile: 5000000

predictions:
    1fm: predictions/X/1fm.dat
    2fm: predictions/X/2fm.dat
    3fm: predictions/X/3fm.dat
    5fm: predictions/X/5fm.dat
    smear:
        enable: false
        rebin: 1

Dmesonperf:
    inputfile: Analysis_output_LHC21dn_TOFPID.root
    ptmins: [1., 2., 3., 4., 6., 8.]
    ptmaxs: [2., 3., 4., 6., 8., 10.]

output:
    file: ALICE3_DDstarbar_pp_PbPb.eps