inputdir: inputs/X

species:
    D: 421
    Dstar: 413

rapidity:
    plot: true

eventsperfile: 1250000

predictions:
    1fm: predictions/Tcc/1fm.dat
    2fm: predictions/Tcc/2fm.dat
    3fm: predictions/Tcc/3fm.dat
    5fm: predictions/Tcc/5fm.dat

Dmesonperf:
    inputfile: Analysis_output_LHC21dn_TOFPID.root
    ptmins: [1., 2., 3., 4., 6., 8.]
    ptmaxs: [2., 3., 4., 6., 8., 10.]

output:
    file: ALICE3_DDstar_pp_PbPb.eps