inputfiles: ['inputs/Tcc/AnalysisResults_101.root',
             'inputs/Tcc/AnalysisResults_102.root',
             'inputs/Tcc/AnalysisResults_103.root',
             'inputs/Tcc/AnalysisResults_104.root',
             'inputs/Tcc/AnalysisResults_105.root',
             'inputs/Tcc/AnalysisResults_106.root',
             'inputs/Tcc/AnalysisResults_107.root',
             'inputs/Tcc/AnalysisResults_108.root',
             'inputs/Tcc/AnalysisResults_109.root',
             'inputs/Tcc/AnalysisResults_110.root',
             'inputs/Tcc/AnalysisResults_111.root',
             'inputs/Tcc/AnalysisResults_112.root',
             'inputs/Tcc/AnalysisResults_113.root',
             'inputs/Tcc/AnalysisResults_114.root',
             'inputs/Tcc/AnalysisResults_115.root',
             'inputs/Tcc/AnalysisResults_115.root',
             'inputs/Tcc/AnalysisResults_117.root',
             'inputs/Tcc/AnalysisResults_118.root',
             'inputs/Tcc/AnalysisResults_119.root',
             'inputs/Tcc/AnalysisResults_120.root',
             'inputs/Tcc/AnalysisResults_121.root',
             'inputs/Tcc/AnalysisResults_122.root',
             'inputs/Tcc/AnalysisResults_123.root',
             'inputs/Tcc/AnalysisResults_124.root',
             'inputs/Tcc/AnalysisResults_125.root',
             'inputs/Tcc/AnalysisResults_126.root',
             'inputs/Tcc/AnalysisResults_127.root',
             'inputs/Tcc/AnalysisResults_128.root',
             'inputs/Tcc/AnalysisResults_129.root',
             'inputs/Tcc/AnalysisResults_130.root',
             'inputs/Tcc/AnalysisResults_131.root',
             'inputs/Tcc/AnalysisResults_132.root',
             'inputs/Tcc/AnalysisResults_133.root',
             'inputs/Tcc/AnalysisResults_134.root',
             'inputs/Tcc/AnalysisResults_135.root',
             'inputs/Tcc/AnalysisResults_136.root',
             'inputs/Tcc/AnalysisResults_137.root',
             'inputs/Tcc/AnalysisResults_138.root',
             'inputs/Tcc/AnalysisResults_139.root',
             'inputs/Tcc/AnalysisResults_140.root',
             'inputs/Tcc/AnalysisResults_141.root',
             'inputs/Tcc/AnalysisResults_142.root',
             'inputs/Tcc/AnalysisResults_143.root',
             'inputs/Tcc/AnalysisResults_144.root',
             'inputs/Tcc/AnalysisResults_145.root',
             'inputs/Tcc/AnalysisResults_146.root',
             'inputs/Tcc/AnalysisResults_147.root',
             'inputs/Tcc/AnalysisResults_148.root',
             'inputs/Tcc/AnalysisResults_149.root',
             'inputs/Tcc/AnalysisResults_150.root',
             'inputs/Tcc/AnalysisResults_151.root',
             'inputs/Tcc/AnalysisResults_152.root',
             'inputs/Tcc/AnalysisResults_153.root',
             'inputs/Tcc/AnalysisResults_154.root',
             'inputs/Tcc/AnalysisResults_155.root',
             'inputs/Tcc/AnalysisResults_156.root',
             'inputs/Tcc/AnalysisResults_157.root',
             'inputs/Tcc/AnalysisResults_158.root',
             'inputs/Tcc/AnalysisResults_159.root',
             'inputs/Tcc/AnalysisResults_160.root',
             'inputs/Tcc/AnalysisResults_161.root',
             'inputs/Tcc/AnalysisResults_162.root',
             'inputs/Tcc/AnalysisResults_163.root',
             'inputs/Tcc/AnalysisResults_164.root',
             'inputs/Tcc/AnalysisResults_165.root',
             'inputs/Tcc/AnalysisResults_166.root',
             'inputs/Tcc/AnalysisResults_167.root',
             'inputs/Tcc/AnalysisResults_168.root',
             'inputs/Tcc/AnalysisResults_169.root',
             'inputs/Tcc/AnalysisResults_170.root',
             'inputs/Tcc/AnalysisResults_171.root',
             'inputs/Tcc/AnalysisResults_172.root',
             'inputs/Tcc/AnalysisResults_173.root',
             'inputs/Tcc/AnalysisResults_174.root',
             'inputs/Tcc/AnalysisResults_175.root',
             'inputs/Tcc/AnalysisResults_176.root',
             'inputs/Tcc/AnalysisResults_177.root',
             'inputs/Tcc/AnalysisResults_178.root',
             'inputs/Tcc/AnalysisResults_179.root',
             'inputs/Tcc/AnalysisResults_180.root',
             'inputs/Tcc/AnalysisResults_201.root',
             'inputs/Tcc/AnalysisResults_202.root',
             'inputs/Tcc/AnalysisResults_203.root',
             'inputs/Tcc/AnalysisResults_204.root',
             'inputs/Tcc/AnalysisResults_205.root',
             'inputs/Tcc/AnalysisResults_206.root',
             'inputs/Tcc/AnalysisResults_207.root',
             'inputs/Tcc/AnalysisResults_208.root',
             'inputs/Tcc/AnalysisResults_209.root',
             'inputs/Tcc/AnalysisResults_210.root',
             'inputs/Tcc/AnalysisResults_211.root',
             'inputs/Tcc/AnalysisResults_212.root',
             'inputs/Tcc/AnalysisResults_213.root',
             'inputs/Tcc/AnalysisResults_214.root',
             'inputs/Tcc/AnalysisResults_215.root',
             'inputs/Tcc/AnalysisResults_215.root',
             'inputs/Tcc/AnalysisResults_217.root',
             'inputs/Tcc/AnalysisResults_218.root',
             'inputs/Tcc/AnalysisResults_219.root',
             'inputs/Tcc/AnalysisResults_220.root',
             'inputs/Tcc/AnalysisResults_221.root',
             'inputs/Tcc/AnalysisResults_222.root',
             'inputs/Tcc/AnalysisResults_223.root',
             'inputs/Tcc/AnalysisResults_224.root',
             'inputs/Tcc/AnalysisResults_225.root',
             'inputs/Tcc/AnalysisResults_226.root',
             'inputs/Tcc/AnalysisResults_227.root',
             'inputs/Tcc/AnalysisResults_228.root',
             'inputs/Tcc/AnalysisResults_229.root',
             'inputs/Tcc/AnalysisResults_230.root',
             'inputs/Tcc/AnalysisResults_231.root',
             'inputs/Tcc/AnalysisResults_232.root',
             'inputs/Tcc/AnalysisResults_233.root',
             'inputs/Tcc/AnalysisResults_234.root',
             'inputs/Tcc/AnalysisResults_235.root',
             'inputs/Tcc/AnalysisResults_235.root',
             'inputs/Tcc/AnalysisResults_238.root',
             'inputs/Tcc/AnalysisResults_238.root',
             'inputs/Tcc/AnalysisResults_239.root',
             'inputs/Tcc/AnalysisResults_240.root',
             'inputs/Tcc/AnalysisResults_241.root',
             'inputs/Tcc/AnalysisResults_242.root',
             'inputs/Tcc/AnalysisResults_243.root',
             'inputs/Tcc/AnalysisResults_244.root',
             'inputs/Tcc/AnalysisResults_245.root',
             'inputs/Tcc/AnalysisResults_246.root',
             'inputs/Tcc/AnalysisResults_247.root',
             'inputs/Tcc/AnalysisResults_248.root',
             'inputs/Tcc/AnalysisResults_249.root',
             'inputs/Tcc/AnalysisResults_250.root',
             'inputs/Tcc/AnalysisResults_251.root',
             'inputs/Tcc/AnalysisResults_252.root',
             'inputs/Tcc/AnalysisResults_253.root',
             'inputs/Tcc/AnalysisResults_254.root',
             'inputs/Tcc/AnalysisResults_255.root',
             'inputs/Tcc/AnalysisResults_256.root',
             'inputs/Tcc/AnalysisResults_257.root',
             'inputs/Tcc/AnalysisResults_258.root',
             'inputs/Tcc/AnalysisResults_259.root',
             'inputs/Tcc/AnalysisResults_260.root',
             'inputs/Tcc/AnalysisResults_261.root',
             'inputs/Tcc/AnalysisResults_262.root',
             'inputs/Tcc/AnalysisResults_263.root',
             'inputs/Tcc/AnalysisResults_264.root',
             'inputs/Tcc/AnalysisResults_265.root',
             'inputs/Tcc/AnalysisResults_266.root',
             'inputs/Tcc/AnalysisResults_267.root',
             'inputs/Tcc/AnalysisResults_268.root',
             'inputs/Tcc/AnalysisResults_269.root',
             'inputs/Tcc/AnalysisResults_270.root',
             'inputs/Tcc/AnalysisResults_271.root',
             'inputs/Tcc/AnalysisResults_272.root',
             'inputs/Tcc/AnalysisResults_273.root',
             'inputs/Tcc/AnalysisResults_274.root',
             'inputs/Tcc/AnalysisResults_275.root',
             'inputs/Tcc/AnalysisResults_276.root',
             'inputs/Tcc/AnalysisResults_277.root',
             'inputs/Tcc/AnalysisResults_278.root',
             'inputs/Tcc/AnalysisResults_279.root',
             'inputs/Tcc/AnalysisResults_280.root']

species:
    D: 421
    Dstar: 413

rapidity:
    plot: false

eventsperfile: 125000

predictions:
    1fm: predictions/Tcc/1fm.dat
    2fm: predictions/Tcc/2fm.dat
    3fm: predictions/Tcc/3fm.dat
    5fm: predictions/Tcc/5fm.dat

Dmesonperf:
    inputfile: Analysis_output_LHC21dn_TOFPID.root
    ptmins: [1., 2., 3., 4., 6., 8.]
    ptmaxs: [2., 3., 4., 6., 8., 10.]
