inputdir: inputs/X

species:
    D: -411
    Dstar: 413

rapidity:
    plot: true

eventsperfile: 5000000

predictions:
    1fm: predictions/X/charged_1fm.dat
    2fm: predictions/X/charged_2fm.dat
    3fm: predictions/X/charged_3fm.dat
    5fm: predictions/X/charged_5fm.dat

Dmesonperf:
    inputfile: Analysis_output_LHC21dn_TOFPID.root
    ptmins: [1., 2., 3., 4., 6., 8.]
    ptmaxs: [2., 3., 4., 6., 8., 10.]

output:
    file: ALICE3_DDstarbar_charged_pp_PbPb.eps